// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtIzbkDzG__KAtsr5Rzjijpw5NpMvMghY',
    appId: '1:976904137383:web:5513f55ac96f9cbc20c982',
    messagingSenderId: '976904137383',
    projectId: 'social-app-74c03',
    authDomain: 'social-app-74c03.firebaseapp.com',
    storageBucket: 'social-app-74c03.appspot.com',
    measurementId: 'G-7ENCSRF3EE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6ndbzUWpop1eHiyZfkyAkFtChX4DojdM',
    appId: '1:976904137383:android:9420340c39ce71c220c982',
    messagingSenderId: '976904137383',
    projectId: 'social-app-74c03',
    storageBucket: 'social-app-74c03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOIumlE2zhatZhugtDUySvz5L8M8KlMrE',
    appId: '1:976904137383:ios:809ba9bc38ce5f3b20c982',
    messagingSenderId: '976904137383',
    projectId: 'social-app-74c03',
    storageBucket: 'social-app-74c03.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOIumlE2zhatZhugtDUySvz5L8M8KlMrE',
    appId: '1:976904137383:ios:809ba9bc38ce5f3b20c982',
    messagingSenderId: '976904137383',
    projectId: 'social-app-74c03',
    storageBucket: 'social-app-74c03.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtIzbkDzG__KAtsr5Rzjijpw5NpMvMghY',
    appId: '1:976904137383:web:2ac3dd2e6241017220c982',
    messagingSenderId: '976904137383',
    projectId: 'social-app-74c03',
    authDomain: 'social-app-74c03.firebaseapp.com',
    storageBucket: 'social-app-74c03.appspot.com',
    measurementId: 'G-RTG0R2K1F2',
  );
}
